version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/var/www
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx/:/var/log/nginx/
    links:
      - phpfpm
  phpfpm:
    build:  
      context: .
      dockerfile: docker/Dockerfile-php
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - .:/var/www
    links:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: docker/Dockerfile-mysql
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=sandbox
        - MYSQL_USER=xo
        - MYSQL_PASSWORD=sandbox
    ports:
        - "3306:3306"
    volumes:
        - "./docker/data/db/mysql:/var/lib/mysql"
